permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 孙博
  email: kingscof@gmail.com
  link: http://imoon.me
  weibo: http://weibo.com/kingscof
  github: https://github.com/kingscof

# 站点信息
title: 孙博的博客 
description: 孙博的博客
url: http://imoon.me
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://en.gravatar.com/userimage/22861507/c99d0be442d75404615623405960d94f.png
favicon: http://en.gravatar.com/userimage/22861507/c99d0be442d75404615623405960d94f.png

# google analytics 设置
ga:
  id: UA-33932111-1
  url: imoon.me

# disqus 设置
disqus:
  shortname: kingscof

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
